name: endorctl scan

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  endorctl-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: 'Run endorctl'
      uses: endorlabs/github-action@d81fa78e334fea6f88e9c89b3077d582cb357a1b
      with:
        namespace: "nathan-staging"
        api: "https://api.staging.endorlabs.com"
        # api_key: ${{ secrets.ENDOR_API_CREDENTIALS_KEY }}
        # api_secret: ${{ secrets.ENDOR_API_CREDENTIALS_SECRET }}
        enable_github_action_token: "true"
        log_verbose: "true"
        log_level: "info"
        ci_run: "true"
        ci_run_tags: "actor=${{ github.actor }},run-id=${{ github.run_id }},pr=${{ env.GITHUB_PR }}"
      env:
        GITHUB_PR: ${{ github.event.number }}
